// Jenkinsfile demo
@Library('ref-solution-pipeliner@feature/19075-RestApiVehicleDetails') _ // Load the my-nested-library as a shared library

//env.pip_create_blob_and_desiredstate = "true"
env.pip_verify_device_with_Id = "true"
env.pip_verify_blob_with_Id = "true"
env.blob_Id = "Tk_AVH_app_test_install"
env.device_Id = "AADemo3"
env.desired_vehicle_id ="43717197-bc95-49bf-b82f-1505d33c14b2"

execRestApi()
